name: adf_cli
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies: 
  http: ^0.13.5
  args: ^2.4.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
